development:
  :address: smtp.server.com
  :port: 25
  :domain: localhost.localdomain
  :authentication: plain
  :user_name: user
  :password: pass
  :tls: true

production:
  :address: smtp.server.com
  :port: 25
  :domain: localhost.localdomain
  :authentication: plain
  :user_name: user
  :password: pass
  :tls: true